spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://47.100.48.12:3306/studywords?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: OMYSQL109
      url: jdbc:mysql://127.0.0.1:3306/studywords?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1234
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnBorrow: false
      # 配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall' 用于防火墙
      filters: stat,wall,slf4j
      # 合并多个DruidDatasource的监控数据
      useGlobalDataSourceStat: true
      # 监控页面配置
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin

  #      stat-view-servlet-enabled: true

  mvc:
    #配置它以后移动html页面就不用改路径了！
    static-path-pattern: /static/**    #静态资源的请求方式


  thymeleaf:
    cache: false
    check-template-location: on
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: true
  main:
    allow-circular-references: true
  web:
    resources:
      static-locations: classpath:/static/

  redis:
    port: 6379
    database: 0
#    host: 47.100.48.12
#    password: omgseu109
    timeout: 3600ms
    client-type: jedis
    lettuce:
      pool:
        max-active: 16
    jedis:
      pool:
        max-active: 16
    host: 127.0.0.1
# 设置word到期时间是一小时
redis:
  key:
    expire:
      word: 3600

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.gao.myspringboot.pojo
  configuration:
    map-underscore-to-camel-case: false #采用驼峰标识




pageSize: 10
scorePerCheck: 50
scoreFinishJob: 100

